{% set name = "looseversion" %}
{% set version = "1.3.0" %}
{% set python_min = "2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebde65f3f6bb9531a81016c6fef3eb95a61181adc47b7f949e9c0ea47911669e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - looseversion
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/effigies/looseversion
  summary: Version numbering for anarchists and software realists
  description: |
    looseversion is a drop-in replacement for the original distutils.version.LooseVersion.
    It implements an identical interface and comparison logic to `LooseVersion`.
    The only major change is that a `looseversion.LooseVersion` is comparable to a
    `distutils.version.LooseVersion`, which means tools should not need to worry whether
    all dependencies that use LooseVersion have migrated.
  license: PSF-2.0
  license_file: LICENSE
  # doc_url: No docs at present. This is where we'd put them.
  dev_url: https://github.com/effigies/looseversion

extra:
  recipe-maintainers:
    - effigies
